version: '3'

services:
  # Node API service
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_DB_URL : mongodb+srv://ribinmathew4u:ribin123@cluster0.6hhccbs.mongodb.net/Homedecor?retryWrites=true&w=majority
      
      CLOUDINARY_URL: cloudinary://127438582472692:P97QGGY0BU8UYD4QDRN-dhI3w3A@dbpbx7tw4
      CLOUD_NAME: dbpbx7tw4
      CLOUD_KEY: "127438582472692"
      CLOUD_SECRET: "P97QGGY0BU8UYD4QDRN-dhI3w3A"
      SESSION_SECRET: "khfihuifgyscghi6543367567vhbjjfgt45475nvjhgjgj+6+9878"
      ADMIN_EMAIL: admin@gmail.com
      ADMIN_PASSWORD: 12345
      KEY_ID: "rzp_test_7gAGPftwtY20XB"
      KEY_SECRETS: "vtqqLXg2NsCftCLpYZShms7M"
    depends_on:
      - mongo_db
    command: sh -c "sleep 10 && node app.js"

  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}
